# Generated by Django 3.0.5 on 2020-05-02 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_member_since'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
