# Generated by Django 3.0.5 on 2020-04-30 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_title', models.CharField(max_length=80)),
                ('issue_description', models.TextField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('ticket_type', models.CharField(choices=[('BUG', 'Bug'), ('FEAT', 'Feature')], default='BUG', max_length=4)),
                ('ticket_status', models.CharField(choices=[('OPN', 'Opened'), ('INP', 'In progress'), ('SOL', 'Solved')], default='OPN', max_length=3)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
